baseURL = 'https://thepragmaticengineer.com/'
theme = 'hugo-mana-theme'
paginate = 10
defaultContentLanguage = 'en'
enableEmoji = true

[params]
  author = 'Cristian'
  description = 'A Software engineer sharing studies, knowledge, and ideas with the community.'
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

[params.social]
  linkedin = 'https://www.linkedin.com/in/cristian-senior-software-engineer/'
  github   = 'https://github.com/cristiantcjti'

[languages]

  [languages.en]
    languageCode  = 'en-us'
    languageName  = 'English'
    weight        = 1
    title         = 'The Pragmatic Engineer'

    [languages.en.params.homeInfoParams]
      Title   = 'Software Engineering is an Art_'
      Content = 'A Software engineer sharing knowledge, studies, notes and real life experiences with the community. Check out the blog posts and if I can contribute somehow with you, the blog will have successfully archived its purpose._'

    [[languages.en.menu.main]]
      name   = 'Home'
      url    = '/'
      weight = 10

    [[languages.en.menu.main]]
      name   = 'About'
      url    = '/about/'
      weight = 20

    [[languages.en.menu.main]]
      name   = 'Blog'
      url    = '/posts/'
      weight = 30

  [languages.pt]
    languageCode  = 'pt-br'
    languageName  = 'Português'
    weight        = 2
    title         = 'The Pragmatic Engineer'

    [languages.pt.params.homeInfoParams]
      Title   = 'Olá, eu sou o Cristian'
      Content = 'Engenheiro backend compartilhando estudos, notas e conhecimento com a comunidade.'

    [[languages.pt.menu.main]]
      name   = 'Inicio'
      url    = '/'
      weight = 10
    
    [[languages.pt.menu.main]]
      name   = 'Sobre'
      url    = '/pt/about/'
      weight = 20

    [[languages.pt.menu.main]]
      name   = 'Blog'
      url    = '/pt/posts/'
      weight = 30

[markup.highlight]
  style     = 'monokai'
  lineNos   = false
  noClasses = false

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false

[params.avatar]
  [params.avatar.home]
    assetPath = "images/software-engineer.jpg"
  [params.avatar.about]
    assetPath = "images/software-engineer.jpg"